@CTI_FieldValidations

  Feature: CTI field validation
    Scenario: validation CTI fields
      Given user is on the OneWorkflow login page
      When user logs in with valid user and password
      Then user successfully logged in to OneWorkflow and agent console should be displayed
      When user clicks on create trouble event
      And user switches to window 1
      Then trouble record form should appear in new tab
      When user clicks on CTI details under sections
      Then user selects category and verifies Type dropdown values then selects Type and verifies item dropdown values

        |category           |               TypeDropdownValues                                                                                                                                   |       Type          |               ItemDropdownValues                                                                                                                                     |
        |1                  |12                                                                                                                                                                  |12                   |ss Network                                                                                                                                                            |
        |Access             |Radio Access Network:RAN:Telia Owned CPE:WLAN:WLAN Access                                                                                                           |Radio Access Network |BSC:eNodeB:GSMCell:MFNCell:nodeB:Repeater:RNC                                                                                                                         |
        |Access             |Radio Access Network:RAN:Telia Owned CPE:WLAN:WLAN Access                                                                                                           |RAN                  |SYNC                                                                                                                                                                  |
        |Access             |Radio Access Network:RAN:Telia Owned CPE:WLAN:WLAN Access                                                                                                           |Telia Owned CPE      |CPE                                                                                                                                                                   |
        |Access             |Radio Access Network:RAN:Telia Owned CPE:WLAN:WLAN Access                                                                                                           |WLAN                 |AP:NAS:PR:R:SAP:SW                                                                                                                                                    |
        |Access             |Radio Access Network:RAN:Telia Owned CPE:WLAN:WLAN Access                                                                                                           |WLAN Access          |SWITCH                                                                                                                                                                |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Analytics            |N/A                                                                                                                                                                   |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |BILLING              |BILLING:Casablanka:First Base:Fokus:ICH:IME:Mobil:NAK:Nobil SE:Openet:Pi3:Policy Manager:Prag:Rio:U                                                                   |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |CHANNEL              |CHANNEL:EFS:VSI                                                                                                                                                       |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Channels             |AKI:Akt                                                                                                                                                               |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |CRM                  |Athene:Blankettwebben:Cusin:eBS Platform:Etray:Frend:GSM-AHS:Homefreewebben:IN-AHS:Kundbild:MAX/Madam:NHF/NWE:PNE:Polweb:RODOD:SDM:SMR_ussd:SuMaS:Tango:Teleopti:Tupp |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Online               |Callme.dk:Lux:Mango:Mit Telia:Mittele.dk:ONLINE:Other:Policy Manager:Telia DK:Telia Home                                                                              |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Online channels      |AKI:Akt:CSS:EFS:EIP:Hades:Selfservice:Telia.dk:VSI                                                                                                                    |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |ORDER                |ORDER                                                                                                                                                                 |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Order mgmt           |NEO                                                                                                                                                                   |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Other                |Callguide:Dynatrace                                                                                                                                                   |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Provisioning         |CAS:CPL:Cusin:Foton:PROVISIONING:State Event                                                                                                                          |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Sales                |AKI:AKT:CPA-webb:Digitalmedia:eDis:FrEnd:JOICE:Kuriren:MA:Megadisc:Mobile Selfservice:Prisma:RFB:SALES:SCA:TUPP:Webshop                                               |
        |BSS                |Analytics:BILLING:CHANNEL:Channels:CRM:Online:Online channels:ORDER:Order mgmt:Other:Provisioning:Sales:Service inventory                                           |Service inventory    |max/madam                                                                                                                                                             |
        |Computer Equipment |Media Storage Devices                                                                                                                                               |Media Storage Devices|Backup Robot                                                                                                                                                          |
        |Computer Services  |Data Services                                                                                                                                                       |Data Services        |Function:Load Balancing Service                                                                                                                                       |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Fixed_IMS            |CFS:DCM:MRS:MSC:MVD:MVS:NSE:OBS:RPAS:SAS:SSC:SSS                                                                                                                      |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|IP                   |DNS                                                                                                                                                                   |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|MESSAGING            |ESA                                                                                                                                                                   |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Mobile CS Core Network|AAA:AFG:BSP:CNDB:DRA:EIR:EPDG:EXTMSC:GGSN:HLR:HSS:IME:IPSMGW:ISITE:MGW:MLC:MNP:MRS:MSC:MSCSERVER:MSS:MTAS:NEBR:ONENDS:RADIUS:SCP:SDN:STN:STP:STX                     |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Mobile IMS Core Network|AAA:AFG:AHUB:CSCF:DRA:DSC:EPDG:IME:IPSMGW:IPWORKS:ISITE:MTAS:SBG                                                                                                    |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Mobile PS Core Network |DNS:EPG:GGSN:LOCAL_CORE:NAT:NLS:PCRF:PGW:PM:RADIUS:SGSN:SHAPERS:TPE-CMIPBB                                                                                          |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Mobile_CS              |IMEI:TIAM                                                                                                                                                           |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Mobile_PS             |CMG:CMM:TDF                                                                                                                                                          |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|NFVI                  |VNF-MANAGER                                                                                                                                                          |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Other                 |BR:FIREWALL:GSS:MIPnet:NLS:NTP:ROUTER:SHAPERS:SPP:SRR                                                                                                                |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Presentation          |Glu_Mobility                                                                                                                                                         |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Software              |CONSOLE                                                                                                                                                              |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Sync                  |IPCKL:SSU                                                                                                                                                            |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|WLAN                  |ALE:AP:APSW:BTR:CNAS:DNNAS:FSERV:LOGGW:NAS:OAS:OPCA:OPS:OSC:OSS:P:PR:R:ROSC:ROUTER:SAS:SW:SWG:TTG                                                                    |
        |Core               |Fixed_IMS:IP:MESSAGING:Mobile CS Core Network:Mobile IMS Core Network:Mobile PS Core Network:Mobile_CS:Mobile_PS:NFVI:Other:Presentation:Software:Sync:WLAN:Workflow|Workflow              |OneWorkflow                                                                                                                                                          |
        |Customer Services  |IT Security:Mobile:Mobile Services:VAS Services                                                                                                                     |IT Security           |Firewall:Network:Proxy:Remote Access                                                                                                                                 |
        |Customer Services  |IT Security:Mobile:Mobile Services:VAS Services                                                                                                                     |Mobile                |Broadband:Enterprise                                                                                                                                                 |
        |Customer Services  |IT Security:Mobile:Mobile Services:VAS Services                                                                                                                     |Mobile Services       |Data:iPhone:Meddelandetjänster:MFN/OE Voice:Nummerportering:Säkerhet- & nöjestjänster:Tal & nät                                                                      |
        |Customer Services  |IT Security:Mobile:Mobile Services:VAS Services                                                                                                                     |VAS Services          |DNS:Mail                                                                                                                                                             |
        |DS                 |MIS                                                                                                                                                                 |MIS                   |VAS                                                                                                                                                                  |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |CGI                   |Leam                                                                                                                                                                 |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Comarch               |Multibella                                                                                                                                                           |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Dataprisma            |- None -                                                                                                                                                             |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Geneva                |- None -                                                                                                                                                             |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Keypro                |- None -                                                                                                                                                             |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Lekab                 |Cstream                                                                                                                                                              |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |TCS                   |Channels:OSS-FI                                                                                                                                                      |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Tieto                 |Billing:Leam BSS:Leam OSS                                                                                                                                            |
        |External           |CGI:Comarch:Dataprisma:Geneva:Keypro:Lekab:TCS:Tieto:Wipro                                                                                                          |Wipro                 |Alpha2                                                                                                                                                               |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Card                  |Fibre Channel HBA card:Network interface card                                                                                                                        |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Data Center           |Chassis:Console Switch                                                                                                                                               |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Device                |Unclassified                                                                                                                                                         |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Power supply          |UPS                                                                                                                                                                  |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Processing Unit       |Cluster Service:Other type of processing unit:Server:Video Streamer                                                                                                  |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Storage               |Disk Library:SAN Switch:Tape Library                                                                                                                                 |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |unclassified          |missed                                                                                                                                                               |
        |Hardware           |Card:Data Center:Device:Disk Device:Hardware:Media Storage Device:Power supply:Processing Unit:Storage:unclassified:Virtual Systems                                 |Virtual Systems       |Cluster                                                                                                                                                              |
        |Internal Service   |Security Service                                                                                                                                                    |Security Service      |PDB Carrier:PDB DK:PDB EE:PDB FI Consumer:PDB FI Enterprise:PDB LT:PDB NO:PDB SE                                                                                     |
        |IOT                |Operation                                                                                                                                                           |Operation             |- None -                                                                                                                                                             |
        |IT                 |Application:Backup:Cloud Infrastructure:Database:DataCenter:Event Management:Network:OSS:Security:Server:Storage                                                    |Application           |Assurance:Billing:CRM:CRM Solutions-FI:Enterprise:JobScheduling-FI:Middleware:Multibella-FI:NMS:OSS:Portal:SAP:Security Services-FI:Tiksu-FI:Tunnustiimi-FI          |
        |Location           |Address:Site                                                                                                                                                        |Address               |Outside                                                                                                                                                              |
        |Location           |Address:Site                                                                                                                                                        |Site                  |IT Site                                                                                                                                                              |













#      And User selects "Category" as dropdownValue and should see values for "notreadonly"
#      And user selects Type as ""